import { SessionProviderProvider } from "@/context/session.context";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Nextjs App Started (Protected)",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}): Promise<ReactNode> {
  const session = await getServerSession();

  return (
    <SessionProviderProvider session={session}>
      {children}
    </SessionProviderProvider>
  );
}
